#
#	SimpleWebKit Makefile
#
TOP = ../..

#
#	SimpleWebKit Object Files
#
OBJS = \
NSURLConnection.o \
NSURLRequest.o \
NSURLResponse.o \
WebDataSource.o \
WebFrame.o \
WebFrameView.o \
WebView.o \

LIBRARY = libWebKit

SUBPROJECTS =

#
#	Include Makefiles 
# 
include $(TOP)/Makefiles/library.make

